version: '3.4'

networks:
  dev:
    driver: bridge

services:
  project-1:
    image: docker.io/library/project1
    depends_on:
      - 'app_db'
    container_name: project1-services
    ports:
      - '8088:80'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=12345;Server=app_db;Port=5432;Database=Teachers; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=teachers
    ports:
      - '5433:5432'
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:
